[tool.black]
line-length = 120
exclude = '''
  /(
  \.eggs
  |\.git
  |\.hg
  |\.mypy_cache
  |\.nox
  |\.tox
  |\.venv
  |_build
  |buck-out
  |build
  |dist
  |node_modules
  )/
'''

[tool.isort]
profile = "black"
force_single_line = true
line_length = 120
force_sort_within_sections = true
no_lines_before = "LOCALFOLDER"
