[tool.black]
line-length = 120
exclude = '''
  /(
  \.eggs
  |\.git
  |\.hg
  |\.mypy_cache
  |\.nox
  |\.tox
  |\.venv
  |_build
  |buck-out
  |build
  |dist
  |node_modules
  )/
'''

[tool.isort]
profile = "black"
force_single_line = true
line_length = 120
force_sort_within_sections = true
no_lines_before = "LOCALFOLDER"

[tool.pytest.ini_options]
xfail_strict=true
norecursedirs = """
    # defaults
    *.egg
    .*
    _darcs
    build
    dist
    venv
    node_modules
    # Extras
    staticfiles
    media
    static
"""
addopts = "--reuse-db"
DJANGO_SETTINGS_MODULE = "pitchdeck.settings"
DJANGO_CONFIGURATION = "Test"
