# Generated by Django 3.2.2 on 2021-05-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_pitchdeck_processed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pitchimage",
            options={"ordering": ["page"]},
        ),
    ]
